name: lawndre_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  font_awesome_flutter: ^10.0.0
  image_picker: ^1.0.8
  http: ^1.2.0
  webview_flutter: 4.8.0
  flutter_map: 6.1.0
  latlong2: 0.9.1
  geocoding: 2.0.0
  flutter: 
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  firebase_analytics: ^11.3.3
  get_storage: ^2.1.1
  video_player: ^2.9.1
  camera: ^0.11.0+2
  path_provider: 2.1.5
  speech_to_text: ^7.0.0
  audioplayers: ^5.2.1

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/Castiron1.png
    - assets/images/google.png
    - assets/images/cuci_gorden.png
    - assets/images/cuci_lipat.png
    - assets/images/cuci_ransel.png
    - assets/images/cuci_setrika.png
    - assets/images/selimut_carpet.png
    - assets/images/cuci_sepatu.png
    - assets/images/jaket.png
    - assets/images/kaos.png
    - assets/images/kemeja.png
    - assets/images/celana.png
    - assets\audio\confirm_sound.mp3
    - assets\audio\simple-notification-152054.mp3
  uses-material-design: true

